package khelp.database.type

enum class DataType(internal val typeSQL: String, internal val defaultValueSerialized: String)
{
    ID("INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY", ""),
    STRING("VARCHAR(8192)", "''"),
    BOOLEAN("BOOLEAN", "FALSE"),
    BYTE("TINYINT", "0"),
    SHORT("SMALLINT", "0"),
    INTEGER("INTEGER", "0"),
    LONG("BIGINT", "0"),
    FLOAT("DOUBLE", "0"),
    DOUBLE("DOUBLE", "0"),
    BYTE_ARRAY("VARCHAR(16384)", "''"),
    CALENDAR("BIGINT", "0"),
    DATE("INTEGER", "0"),
    TIME("INTEGER", "0"),
    ENUM("VARCHAR(1024)", "");

    fun compatible(type: DataType) =
        this == type || ((this == DataType.ID || this == DataType.INTEGER) && (type == DataType.ID || type == DataType.INTEGER))
}